name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: |
          docker build \
            -t swatikadam16/client-a-node-app:${{ github.sha }} \
            .

      - name: Push Docker image to Docker Hub
        run: |
          docker push swatikadam16/client-a-node-app:${{ github.sha }}
  

      - name: Test SSH connection
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \
          "echo ✅ Connected successfully to $(hostname)"

      - name: Deploy to Docker Swarm
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > private_key.pem
          chmod 600 private_key.pem

          echo "Deploying new image on remote Swarm manager..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST <<EOF
          docker service update \
            --image swatikadam16/client-a-node-app:${{ github.sha }} \
            multi-client_client-a
          EOF